version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket larrysambucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: ZIP
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
    - sourcecode/*

