AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  inputfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: inputdata.inputdata_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::411658317626:role/service-role/inputfunction-role-yzndufg1'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /inputdata
            Method: POST
